[functions.send-whatsapp]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.complete-emergency]
verify_jwt = false

[functions.send-registration-otp]
verify_jwt = false

[functions.verify-registration-otp]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

