import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface Translations { [key: string]: { ar: string; en: string; }; }

const translations: Translations = {
  'header.adminPanel': { ar: 'لوحة الأدمن', en: 'Admin Panel' },
  'header.dashboard': { ar: 'لوحة التحكم', en: 'Dashboard' },
  'header.myAccount': { ar: 'حسابي', en: 'My Account' },
  'header.login': { ar: 'تسجيل', en: 'Login' },
  'header.displayPages': { ar: 'صفحات العرض', en: 'Display Pages' },
  'header.tabkhaty': { ar: 'خدمات', en: 'Khadamat' },
  'header.contactUs': { ar: 'تواصل معنا', en: 'Contact Us' },
  'header.home': { ar: 'الرئيسية', en: 'Home' },
  'index.browseProducts': { ar: 'تصفح خدمات مقدمي الخدمات', en: 'Browse Service Providers' },
  'index.discoverBest': { ar: 'اكتشف أفضل الخدمات', en: 'Discover the Best Services' },
  'index.browseDesc': { ar: 'تصفح خدمات من مختلف مقدمي الخدمات واطلب مباشرة', en: 'Browse services from various providers and order directly' },
  'index.loginToShop': { ar: 'سجل لتبدأ التسوق', en: 'Sign up to start shopping' },
  'index.searchPlaceholder': { ar: 'ابحث عن خدمة أو مقدم خدمة...', en: 'Search for a service or provider...' },
  'index.products': { ar: 'الخدمات', en: 'Services' },
  'index.product': { ar: 'خدمة', en: 'service' },
  'index.noProducts': { ar: 'لا توجد خدمات', en: 'No services' },
  'index.tryDifferent': { ar: 'جرب البحث بكلمات مختلفة', en: 'Try different search terms' },
  'index.noProductsYet': { ar: 'لم يتم إضافة خدمات بعد', en: 'No services added yet' },
  'index.areMerchant': { ar: 'هل أنت مقدم خدمة؟', en: 'Are you a service provider?' },
  'index.registerNow': { ar: 'سجل الآن وأضف خدماتك', en: 'Register now and add your services' },
  'index.add': { ar: 'أضف', en: 'Add' },
  'index.registerCustomer': { ar: 'سجل كعميل', en: 'Register as Customer' },
  'index.registerMerchant': { ar: 'سجل كمقدم خدمة', en: 'Register as Service Provider' },
  'index.termsConditions': { ar: 'الشروط والأحكام', en: 'Terms & Conditions' },
  'index.allRights': { ar: 'جميع الحقوق محفوظة', en: 'All rights reserved' },
  'index.tabkhatyRights': { ar: 'خدمات - جميع الحقوق محفوظة', en: 'Khadamat - All rights reserved' },
  'index.tabkhatyPlatform': { ar: 'منصة خدمات', en: 'Khadamat Platform' },
  'index.heroTitle': { ar: 'خدمات … كل خدماتك بمكان واحد', en: 'Khadamat … All your services in one place' },
  'index.heroSubtitle': { ar: 'منصة الخدمات المنزلية الأولى', en: 'The first home services platform' },
  'index.heroDesc': { ar: 'منصة الخدمات المنزلية الأولى. اعرض خدماتك وتواصل مع العملاء بسهولة.', en: 'The first home services platform. Display your services and connect with customers easily.' },
  'index.startNow': { ar: 'ابدأ الآن', en: 'Start Now' },
  'index.browseServices': { ar: 'استكشف الخدمات', en: 'Browse Services' },
  'index.registerAsCook': { ar: 'سجل الآن كمقدم خدمة', en: 'Register as a Service Provider' },
  'index.shopNow': { ar: 'تصفح الخدمات', en: 'Browse Services' },
  'index.myKitchen': { ar: 'خدمتي', en: 'My Service' },
  'index.freeTrialMonth': { ar: '+ اشتراك مجاني لمدة شهرين', en: '+ Free subscription for two months' },
  'index.startNowCTA': { ar: '🔧 ابدأ مشروعك الآن!', en: '🔧 Start Your Project Now!' },
  'index.joinPlatform': { ar: 'انضم لمنصة خدمات وحوّل مهاراتك إلى مصدر دخل حقيقي', en: 'Join Khadamat platform and turn your skills into a real income source' },
  'index.seeAll': { ar: 'استكشف المزيد', en: 'Explore More' },
  'index.latestDishes': { ar: 'أحدث الخدمات', en: 'Latest Services' },
  'index.heroMainTitle': { ar: 'كل خدماتك بمكان واحد', en: 'All your services in one place' },
  'index.heroMainHighlight': { ar: 'خدماتك', en: 'services' },
  'index.heroMainPrefix': { ar: 'كل ', en: 'All your ' },
  'index.heroMainSuffix': { ar: ' بمكان واحد', en: ' in one place' },
  'index.heroDescription': { ar: 'منصة تربط مقدمي الخدمات المنزلية بالعملاء بسهولة وسرعة', en: 'A platform connecting home service providers with customers easily and quickly' },
  'index.registerAsProvider': { ar: 'سجل كمقدم خدمة', en: 'Register as Provider' },
  'index.contactKhadamat': { ar: 'تواصل معنا', en: 'Contact Khadamat' },
  'index.chooseService': { ar: 'او تصفح سوق خدمات', en: 'Choose the service you are looking for' },
  'index.emergencySearch': { ar: '🚨 صيانة طارئة', en: '🚨 Emergency Maintenance' },
  'index.emergencyOrders': { ar: '🚨 الطلبات الطارئة', en: '🚨 Emergency Orders' },
  'index.loginFirst': { ar: 'يجب تسجيل الدخول أولاً', en: 'You must login first' },
  'header.myStore': { ar: 'متجري', en: 'My Store' },
  'header.addService': { ar: 'أضف خدمتك', en: 'Add Your Service' },
  'header.loginProvider': { ar: 'سجل حرفي الآن', en: 'Register Now' },
  'service.parcelDelivery': { ar: 'توصيل طرود', en: 'Parcel Delivery' },
  'service.waterTanks': { ar: 'صهاريج مياه', en: 'Water Tankers' },
  'service.electrician': { ar: 'كهربجي', en: 'Electrician' },
  'service.applianceMaintenance': { ar: 'صيانة الأجهزة المنزلية', en: 'Appliance Maintenance' },
  'service.plumber': { ar: 'موسرجي', en: 'Plumber' },
  'service.carpenter': { ar: 'نجّار', en: 'Carpenter' },
  'service.homeDecor': { ar: 'ديكور منزلي', en: 'Home Decor' },
  'service.cleaning': { ar: 'تنظيف ودراي كلين', en: 'Cleaning & Dry Clean' },
  'service.furnitureMoving': { ar: 'نقل أثاث', en: 'Furniture Moving' },
  'service.blacksmith': { ar: 'حداد، زجاج، ألمنيوم', en: 'Blacksmith, Glass & Aluminum' },
  'service.waterFuel': { ar: 'غاز ومحروقات', en: 'Gas & Fuel' },
  'service.roadMechanic': { ar: 'ميكانيكي طرقات', en: 'Road Mechanic' },
  'service.towTrucks': { ar: 'ونشات', en: 'Tow Trucks' },
  'categories.all': { ar: 'الكل', en: 'All' },
  'categories.parcelDelivery': { ar: 'توصيل طرود', en: 'Parcel Delivery' },
  'categories.waterTanks': { ar: 'صهاريج مياه', en: 'Water Tankers' },
  'categories.gasFuel': { ar: 'غاز ومحروقات', en: 'Gas & Fuel' },
  'categories.furnitureMoving': { ar: 'نقل أثاث', en: 'Furniture Moving' },
  'categories.electrician': { ar: 'كهربجي', en: 'Electrician' },
  'categories.plumber': { ar: 'موسرجي', en: 'Plumber' },
  'categories.carpenter': { ar: 'نجّار', en: 'Carpenter' },
  'categories.blacksmith': { ar: 'حداد، زجاج، ألمنيوم', en: 'Blacksmith, Glass & Aluminum' },
  'categories.homeDecor': { ar: 'ديكور منزلي', en: 'Home Decor' },
  'categories.cleaning': { ar: 'تنظيف ودراي كلين', en: 'Cleaning & Dry Clean' },
  'categories.roadMechanic': { ar: 'ميكانيكي طرقات', en: 'Road Mechanic' },
  'categories.towTrucks': { ar: 'ونشات', en: 'Tow Trucks' },
  'categories.applianceRepair': { ar: 'صيانة الأجهزة المنزلية', en: 'Appliance Maintenance' },
  'auth.welcome': { ar: 'مرحباً بك', en: 'Welcome' },
  'auth.chooseAccount': { ar: 'اختر نوع حسابك', en: 'Choose your account type' },
  'auth.customer': { ar: 'عميل', en: 'Customer' },
  'auth.forShopping': { ar: 'للتسوق والشراء', en: 'For shopping and buying' },
  'auth.merchant': { ar: 'مقدم خدمة', en: 'Service Provider' },
  'auth.forProducts': { ar: 'لعرض الخدمات', en: 'To display services' },
  'auth.login': { ar: 'تسجيل الدخول', en: 'Login' },
  'auth.newAccount': { ar: 'حساب جديد', en: 'New Account' },
  'auth.phone': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'auth.password': { ar: 'كلمة المرور', en: 'Password' },
  'auth.confirmPassword': { ar: 'تأكيد كلمة المرور', en: 'Confirm Password' },
  'auth.agreeTerms': { ar: 'أوافق على', en: 'I agree to' },
  'auth.termsLink': { ar: 'الشروط والأحكام وسياسة الخصوصية', en: 'Terms & Conditions and Privacy Policy' },
  'auth.loggingIn': { ar: 'جاري تسجيل الدخول...', en: 'Logging in...' },
  'auth.creatingAccount': { ar: 'جاري إنشاء الحساب...', en: 'Creating account...' },
  'auth.createAccount': { ar: 'إنشاء حساب', en: 'Create Account' },
  'auth.backHome': { ar: 'العودة للصفحة الرئيسية', en: 'Back to Home' },
  'auth.loginError': { ar: 'خطأ في تسجيل الدخول', en: 'Login Error' },
  'auth.wrongCredentials': { ar: 'رقم الهاتف أو كلمة المرور غير صحيحة', en: 'Wrong phone number or password' },
  'auth.accountExists': { ar: 'الحساب موجود مسبقاً', en: 'Account already exists' },
  'auth.phoneExists': { ar: 'هذا الرقم مسجل بالفعل', en: 'This phone is already registered' },
  'auth.registerError': { ar: 'خطأ في التسجيل', en: 'Registration Error' },
  'auth.registerSuccess': { ar: 'تم التسجيل بنجاح!', en: 'Registration successful!' },
  'auth.welcomeMerchant': { ar: 'مرحباً بك، يمكنك الآن إضافة خدماتك', en: 'Welcome! You can now add your services' },
  'auth.welcomeCustomer': { ar: 'مرحباً بك، يمكنك الآن التسوق', en: 'Welcome! You can now shop' },
  'auth.loginRequired': { ar: 'سجل دخولك أولاً', en: 'Please login first' },
  'auth.loginToCart': { ar: 'يجب تسجيل الدخول لإضافة خدمات للسلة', en: 'Login to add services to cart' },
  'auth.notForMerchants': { ar: 'غير متاح لمقدمي الخدمات', en: 'Not available for service providers' },
  'auth.merchantCantBuy': { ar: 'حساب مقدم الخدمة لا يمكنه الشراء. سجل كعميل للتسوق.', en: 'Service provider account cannot purchase. Register as customer to shop.' },
  'auth.phoneInvalid': { ar: 'رقم الهاتف غير صالح', en: 'Invalid phone number' },
  'auth.phoneTooLong': { ar: 'رقم الهاتف طويل جداً', en: 'Phone number is too long' },
  'auth.passwordMin': { ar: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل', en: 'Password must be at least 6 characters' },
  'auth.passwordMismatch': { ar: 'كلمات المرور غير متطابقة', en: 'Passwords do not match' },
  'auth.agreeRequired': { ar: 'يجب الموافقة على الشروط والأحكام', en: 'You must agree to the terms' },
  'auth.forgotPassword': { ar: 'نسيت كلمة المرور؟', en: 'Forgot Password?' },
  'auth.resetPassword': { ar: 'إعادة تعيين كلمة المرور', en: 'Reset Password' },
  'auth.enterPhoneReset': { ar: 'أدخل رقم هاتفك لإعادة تعيين كلمة المرور', en: 'Enter your phone number to reset password' },
  'auth.sendCode': { ar: 'إرسال الكود', en: 'Send Code' },
  'auth.enterOtp': { ar: 'أدخل كود التحقق', en: 'Enter verification code' },
  'auth.codeSentTo': { ar: 'تم إرسال الكود إلى', en: 'Code sent to' },
  'auth.validFor': { ar: 'صالح لمدة 5 دقائق', en: 'Valid for 5 minutes' },
  'auth.verify': { ar: 'تحقق', en: 'Verify' },
  'auth.resendCode': { ar: 'إعادة إرسال الكود', en: 'Resend Code' },
  'auth.resendIn': { ar: 'إعادة الإرسال بعد', en: 'Resend in' },
  'auth.newPassword': { ar: 'كلمة المرور الجديدة', en: 'New Password' },
  'auth.enterNewPassword': { ar: 'أدخل كلمة المرور الجديدة', en: 'Enter your new password' },
  'auth.changePassword': { ar: 'تغيير كلمة المرور', en: 'Change Password' },
  'auth.passwordChanged': { ar: 'تم تغيير كلمة المرور بنجاح!', en: 'Password changed successfully!' },
  'auth.canLoginNow': { ar: 'يمكنك تسجيل الدخول الآن', en: 'You can login now' },
  'auth.phoneNotFound': { ar: 'رقم الهاتف غير مسجل', en: 'Phone number not registered' },
  'auth.invalidOtp': { ar: 'كود التحقق غير صحيح', en: 'Invalid verification code' },
  'auth.otpExpired': { ar: 'انتهت صلاحية الكود، اطلب رمزاً جديداً', en: 'Code expired, request a new one' },
  'auth.otpSent': { ar: 'تم إرسال الكود بنجاح', en: 'Code sent successfully' },
  'auth.checkWhatsApp': { ar: 'تحقق من رسائل WhatsApp', en: 'Check your WhatsApp messages' },
  'auth.rateLimited': { ar: 'تم تجاوز الحد الأقصى للمحاولات. حاول بعد ساعة.', en: 'Too many attempts. Try again in an hour.' },
  'auth.sendOtpFailed': { ar: 'فشل في إرسال الكود', en: 'Failed to send code' },
  'auth.verifyOtpFailed': { ar: 'فشل في التحقق من الكود', en: 'Failed to verify code' },
  'auth.tokenExpired': { ar: 'انتهت صلاحية الجلسة، أعد المحاولة', en: 'Session expired, please try again' },
  'auth.resetPasswordFailed': { ar: 'فشل في تغيير كلمة المرور', en: 'Failed to change password' },
  'auth.changePhone': { ar: 'تغيير رقم الهاتف', en: 'Change phone number' },
  'dashboard.title': { ar: 'لوحة التحكم', en: 'Dashboard' },
  'dashboard.logout': { ar: 'تسجيل الخروج', en: 'Logout' },
  'dashboard.orders': { ar: 'الطلبات', en: 'Orders' },
  'dashboard.products': { ar: 'الخدمات', en: 'Services' },
  'dashboard.profile': { ar: 'الملف', en: 'Profile' },
  'dashboard.payments': { ar: 'الدفع', en: 'Payments' },
  'dashboard.disclaimer': { ar: 'المنصة تؤجّر صفحات عرض رقمية فقط، وليست متجرًا إلكترونيًا', en: 'This platform only rents digital display pages, it is not an e-commerce store' },
  'payment.cliqTitle': { ar: 'الدفع عبر CliQ', en: 'Pay via CliQ' },
  'payment.cliqDesc': { ar: 'ادفع اشتراكك الشهري عبر CliQ وارفع الوصل', en: 'Pay your monthly subscription via CliQ and upload the receipt' },
  'payment.cliqAlias': { ar: 'الاسم المستعار', en: 'CliQ Alias' },
  'payment.amount': { ar: 'المبلغ', en: 'Amount' },
  'payment.jod': { ar: 'دينار أردني', en: 'JOD' },
  'payment.usd': { ar: 'دولار', en: 'USD' },
  'payment.instructions': { ar: 'بعد التحويل، ارفع صورة الوصل وانتظر موافقة الإدارة لتفعيل صفحتك', en: 'After transfer, upload the receipt image and wait for admin approval to activate your page' },
  'payment.uploadReceipt': { ar: 'رفع وصل الدفع', en: 'Upload Payment Receipt' },
  'payment.selectImage': { ar: 'اختر صورة الوصل', en: 'Select receipt image' },
  'payment.sendReceipt': { ar: 'إرسال الوصل', en: 'Send Receipt' },
  'payment.uploading': { ar: 'جاري الرفع...', en: 'Uploading...' },
  'payment.history': { ar: 'سجل المدفوعات', en: 'Payment History' },
  'payment.noReceipts': { ar: 'لم ترفع أي وصولات بعد', en: 'No receipts uploaded yet' },
  'payment.approved': { ar: 'مقبول', en: 'Approved' },
  'payment.rejected': { ar: 'مرفوض', en: 'Rejected' },
  'payment.pending': { ar: 'قيد المراجعة', en: 'Pending' },
  'payment.uploadSuccess': { ar: 'تم رفع الوصل بنجاح', en: 'Receipt uploaded successfully' },
  'payment.waitReview': { ar: 'سيتم مراجعته من الإدارة قريباً', en: 'It will be reviewed by admin soon' },
  'payment.uploadFailed': { ar: 'فشل في رفع الوصل', en: 'Failed to upload receipt' },
  'payment.fileTooLarge': { ar: 'الملف كبير جداً', en: 'File is too large' },
  'payment.maxSize': { ar: 'الحد الأقصى 5 ميجابايت', en: 'Maximum size is 5MB' },
  'payment.stripeTitle': { ar: 'الدفع عبر Stripe', en: 'Pay via Stripe' },
  'payment.stripeDesc': { ar: 'ادفع اشتراكك الشهري ببطاقتك الائتمانية', en: 'Pay your monthly subscription with your credit card' },
  'payment.stripeClosed': { ar: 'مغلق حالياً', en: 'Currently closed' },
  'payment.stripePay': { ar: 'ادفع الآن', en: 'Pay Now' },
  'payment.receiptUploaded': { ar: 'تم رفع الوصل', en: 'Receipt uploaded' },
  'payment.receiptUploadedDesc': { ar: 'سيتم مراجعته قريباً', en: 'Will be reviewed soon' },
  'payment.whatsappSupport': { ar: 'تواصل معنا عبر واتساب للمساعدة في الدفع', en: 'Contact us on WhatsApp for payment help' },
  'subscription.status': { ar: 'حالة الاشتراك', en: 'Subscription Status' },
  'subscription.days': { ar: 'يوم', en: 'days' },
  'subscription.remaining': { ar: 'متبقي', en: 'remaining' },
  'subscription.expired': { ar: 'انتهى اشتراكك', en: 'Your subscription expired' },
  'subscription.renewNow': { ar: 'جدد اشتراكك لإعادة تفعيل صفحتك', en: 'Renew your subscription to reactivate your page' },
  'subscription.freeTrial': { ar: 'اشتراك مجاني!', en: 'Free Subscription!' },
  'subscription.freeMonth': { ar: 'شهرين مجاناً', en: 'Free 2 Months' },
  'subscription.freeTrialDesc': { ar: 'ابدأ اشتراكك المجاني لمدة شهرين بدون أي دفع', en: 'Start your free 2-month subscription without any payment' },
  'subscription.trialDuration': { ar: 'مدة الاشتراك', en: 'Subscription Duration' },
  'subscription.startTrial': { ar: 'ابدأ الاشتراك المجاني (شهرين)', en: 'Start Free Subscription (2 Months)' },
  'subscription.starting': { ar: 'جاري البدء...', en: 'Starting...' },
  'subscription.trialStarted': { ar: 'تم بدء الاشتراك المجاني!', en: 'Free subscription started!' },
  'subscription.trialStartedDesc': { ar: 'يمكنك الآن إضافة خدماتك لمدة شهرين', en: 'You can now add your services for 2 months' },
  'subscription.trialError': { ar: 'فشل في بدء الاشتراك المجاني', en: 'Failed to start free subscription' },
  'subscription.freeTrialActive': { ar: 'الاشتراك المجاني نشط', en: 'Free Subscription Active' },
  'subscription.free': { ar: 'مجاني', en: 'FREE' },
  'subscription.freeTrialAvailable': { ar: 'الاشتراك المجاني متاح!', en: 'Free Subscription Available!' },
  'subscription.startFreeTrial': { ar: 'ابدأ الاشتراك المجاني (شهرين)', en: 'Start Free Subscription (2 Months)' },
  'subscription.trialActivated': { ar: 'تم تفعيل الاشتراك المجاني!', en: 'Free subscription activated!' },
  'subscription.trialActivatedDesc': { ar: 'يمكنك الآن رفع خدماتك لمدة شهرين', en: 'You can now upload your services for 2 months' },
  'service.dailyWorker': { ar: 'عامل يومي', en: 'Daily Worker' },
  'subscription.expiresOn': { ar: 'ينتهي في', en: 'Expires on' },
  'subscription.daysLeft': { ar: 'يوم متبقي', en: 'days left' },
  'subscription.renewSoon': { ar: 'قم بتجديد اشتراكك قريباً لتجنب إيقاف صفحتك', en: 'Renew your subscription soon to avoid page deactivation' },
  'public.disclaimer': { ar: 'المنصة تؤجّر صفحات عرض رقمية فقط، وليست متجرًا إلكترونيًا', en: 'This platform only rents digital display pages, it is not an e-commerce store' },
  'public.notFound': { ar: 'الصفحة غير موجودة', en: 'Page not found' },
  'public.notAvailable': { ar: 'هذه الصفحة غير متاحة أو تم تعطيلها', en: 'This page is not available or has been disabled' },
  'public.noName': { ar: 'بدون اسم', en: 'No name' },
  'public.hasDelivery': { ar: 'يوجد توصيل', en: 'Delivery available' },
  'public.call': { ar: 'اتصال', en: 'Call' },
  'public.whatsapp': { ar: 'واتساب', en: 'WhatsApp' },
  'public.productsServices': { ar: 'الخدمات', en: 'Services' },
  'public.noItems': { ar: 'لا توجد خدمات للعرض حالياً', en: 'No services to display currently' },
  'public.salesDisclaimer': { ar: 'جميع عمليات البيع والدفع تتم مباشرة مع صاحب الصفحة', en: 'All sales and payments are done directly with the page owner' },
  'public.phone': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'public.copied': { ar: 'تم النسخ', en: 'Copied' },
  'public.phoneCopied': { ar: 'تم نسخ رقم الهاتف', en: 'Phone number copied' },
  'public.addToCart': { ar: 'أضف للسلة', en: 'Add to Cart' },
  'admin.title': { ar: 'لوحة الأدمن', en: 'Admin Panel' },
  'admin.totalMerchants': { ar: 'إجمالي مقدمي الخدمات', en: 'Total Service Providers' },
  'admin.activeStores': { ar: 'الصفحات النشطة', en: 'Active Pages' },
  'admin.pendingReceipts': { ar: 'وصولات قيد المراجعة', en: 'Pending Receipts' },
  'admin.merchants': { ar: 'مقدمي الخدمات', en: 'Providers' },
  'admin.payments': { ar: 'المدفوعات', en: 'Payments' },
  'admin.manageMerchants': { ar: 'إدارة مقدمي الخدمات', en: 'Manage Service Providers' },
  'admin.viewManageMerchants': { ar: 'عرض وإدارة جميع مقدمي الخدمات المسجلين', en: 'View and manage all registered service providers' },
  'admin.noMerchants': { ar: 'لا يوجد مقدمي خدمات', en: 'No service providers' },
  'admin.name': { ar: 'الاسم', en: 'Name' },
  'admin.phone': { ar: 'الهاتف', en: 'Phone' },
  'admin.link': { ar: 'الرابط', en: 'Link' },
  'admin.status': { ar: 'الحالة', en: 'Status' },
  'admin.actions': { ar: 'الإجراءات', en: 'Actions' },
  'admin.active': { ar: 'نشط', en: 'Active' },
  'admin.closed': { ar: 'مغلق', en: 'Closed' },
  'admin.close': { ar: 'إغلاق', en: 'Close' },
  'admin.activate': { ar: 'تفعيل', en: 'Activate' },
  'admin.managePayments': { ar: 'إدارة المدفوعات', en: 'Manage Payments' },
  'admin.reviewReceipts': { ar: 'مراجعة وصولات الدفع من مقدمي الخدمات', en: 'Review payment receipts from service providers' },
  'admin.noReceipts': { ar: 'لا توجد وصولات', en: 'No receipts' },
  'admin.merchant': { ar: 'مقدم الخدمة', en: 'Provider' },
  'admin.amount': { ar: 'المبلغ', en: 'Amount' },
  'admin.month': { ar: 'الشهر', en: 'Month' },
  'admin.approved': { ar: 'مقبول', en: 'Approved' },
  'admin.rejected': { ar: 'مرفوض', en: 'Rejected' },
  'admin.pending': { ar: 'قيد المراجعة', en: 'Pending' },
  'admin.previewReceipt': { ar: 'معاينة الوصل', en: 'Preview Receipt' },
  'admin.receiptImage': { ar: 'صورة وصل الدفع المرفوعة من مقدم الخدمة', en: 'Payment receipt image uploaded by provider' },
  'admin.storeClosed': { ar: 'تم إغلاق الصفحة', en: 'Page closed' },
  'admin.storeActivated': { ar: 'تم تفعيل الصفحة', en: 'Page activated' },
  'admin.receiptApproved': { ar: 'تم قبول الوصل', en: 'Receipt approved' },
  'admin.receiptRejected': { ar: 'تم رفض الوصل', en: 'Receipt rejected' },
  'admin.productsTab': { ar: 'الخدمات', en: 'Services' },
  'admin.manageProducts': { ar: 'إدارة الخدمات', en: 'Manage Services' },
  'admin.deleteProducts': { ar: 'حذف أي خدمة من جميع مقدمي الخدمات', en: 'Delete any service from all providers' },
  'admin.noProducts': { ar: 'لا توجد خدمات', en: 'No services' },
  'admin.product': { ar: 'الخدمة', en: 'Service' },
  'admin.price': { ar: 'السعر', en: 'Price' },
  'admin.owner': { ar: 'صاحب الخدمة', en: 'Owner' },
  'admin.deleteProduct': { ar: 'حذف', en: 'Delete' },
  'admin.productDeleted': { ar: 'تم حذف الخدمة', en: 'Service deleted' },
  'admin.confirmDelete': { ar: 'هل أنت متأكد من حذف هذه الخدمة؟', en: 'Are you sure you want to delete this service?' },
  'admin.deleteMerchant': { ar: 'حذف', en: 'Delete' },
  'admin.merchantDeleted': { ar: 'تم حذف مقدم الخدمة بنجاح', en: 'Service provider deleted successfully' },
  'admin.confirmDeleteMerchant': { ar: 'هل أنت متأكد من حذف مقدم الخدمة هذا بجميع بياناته؟ لا يمكن التراجع عن هذا الإجراء.', en: 'Are you sure you want to delete this provider and all their data? This action cannot be undone.' },
  'common.loading': { ar: 'جاري التحميل...', en: 'Loading...' },
  'common.error': { ar: 'حدث خطأ', en: 'An error occurred' },
  'common.save': { ar: 'حفظ', en: 'Save' },
  'common.cancel': { ar: 'إلغاء', en: 'Cancel' },
  'common.currency': { ar: 'ر.س', en: 'SAR' },
  'common.back': { ar: 'رجوع', en: 'Back' },
  'common.view': { ar: 'عرض', en: 'View' },
  'common.approve': { ar: 'قبول', en: 'Approve' },
  'common.reject': { ar: 'رفض', en: 'Reject' },
  'common.noName': { ar: 'بدون اسم', en: 'No name' },
  'common.delete': { ar: 'حذف', en: 'Delete' },
  'common.add': { ar: 'إضافة', en: 'Add' },
  'common.edit': { ar: 'تعديل', en: 'Edit' },
  'common.update': { ar: 'تحديث', en: 'Update' },
  'customer.myAccount': { ar: 'حسابي', en: 'My Account' },
  'customer.logout': { ar: 'تسجيل الخروج', en: 'Logout' },
  'customer.profile': { ar: 'الملف الشخصي', en: 'Profile' },
  'customer.name': { ar: 'الاسم', en: 'Name' },
  'customer.namePlaceholder': { ar: 'اسمك', en: 'Your name' },
  'customer.phone': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'customer.saving': { ar: 'جاري الحفظ...', en: 'Saving...' },
  'customer.save': { ar: 'حفظ', en: 'Save' },
  'customer.myOrders': { ar: 'طلباتي', en: 'My Orders' },
  'customer.noOrders': { ar: 'لا توجد طلبات بعد', en: 'No orders yet' },
  'customer.browseProducts': { ar: 'تصفح الخدمات', en: 'Browse Services' },
  'customer.saveError': { ar: 'فشل في حفظ البيانات', en: 'Failed to save data' },
  'customer.saved': { ar: 'تم الحفظ', en: 'Saved' },
  'customer.dataUpdated': { ar: 'تم تحديث بياناتك', en: 'Your data has been updated' },
  'profile.error': { ar: 'خطأ', en: 'Error' },
  'profile.loadError': { ar: 'فشل في تحميل الملف الشخصي', en: 'Failed to load profile' },
  'profile.notFound': { ar: 'لم يتم العثور على الملف الشخصي', en: 'Profile not found' },
  'profile.imageUploaded': { ar: 'تم رفع الصورة', en: 'Image uploaded' },
  'profile.avatarUpdated': { ar: 'تم تحديث صورة البروفايل', en: 'Profile image updated' },
  'profile.coverUpdated': { ar: 'تم تحديث صورة الغلاف', en: 'Cover image updated' },
  'profile.deleted': { ar: 'تم الحذف', en: 'Deleted' },
  'profile.avatarDeleted': { ar: 'تم حذف صورة البروفايل', en: 'Profile image deleted' },
  'profile.coverDeleted': { ar: 'تم حذف صورة الغلاف', en: 'Cover image deleted' },
  'profile.saveError': { ar: 'فشل في حفظ التغييرات', en: 'Failed to save changes' },
  'profile.saved': { ar: 'تم الحفظ', en: 'Saved' },
  'profile.profileUpdated': { ar: 'تم تحديث الملف الشخصي بنجاح', en: 'Profile updated successfully' },
  'profile.linkCopied': { ar: 'تم النسخ', en: 'Copied' },
  'profile.pageLinkCopied': { ar: 'تم نسخ رابط صفحتك', en: 'Your page link copied' },
  'profile.changeCover': { ar: 'تغيير الغلاف', en: 'Change cover' },
  'profile.imagesNote': { ar: 'صورة البروفايل والغلاف ستظهر في صفحتك العامة. يتم ضغط الصور تلقائياً.', en: 'Profile and cover images will appear on your public page. Images are automatically compressed.' },
  'profile.pageStatus': { ar: 'حالة الصفحة', en: 'Page Status' },
  'profile.pageEnabled': { ar: 'صفحتك مفعّلة ومرئية للزوار', en: 'Your page is active and visible to visitors' },
  'profile.pageDisabled': { ar: 'صفحتك معطّلة وغير مرئية', en: 'Your page is disabled and not visible' },
  'profile.profileInfo': { ar: 'معلومات الملف الشخصي', en: 'Profile Information' },
  'profile.profileInfoDesc': { ar: 'هذه المعلومات ستظهر في صفحتك العامة', en: 'This information will appear on your public page' },
  'profile.displayName': { ar: 'نوع الخدمة', en: 'Service Type' },
  'profile.displayNamePlaceholder': { ar: 'اختر نوع الخدمة', en: 'Select service type' },
  'profile.bio': { ar: 'نبذة عنك', en: 'About You' },
  'profile.bioPlaceholder': { ar: 'وصف مختصر عن خدماتك...', en: 'A brief description of your services...' },
  'profile.pageLink': { ar: 'رابط المتجر', en: 'Store Link' },
  'profile.contactInfo': { ar: 'معلومات التواصل', en: 'Contact Information' },
  'profile.phone': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'profile.phoneCantChange': { ar: 'لا يمكن تغيير رقم الهاتف', en: 'Phone number cannot be changed' },
  'profile.whatsapp': { ar: 'رقم واتساب', en: 'WhatsApp Number' },
  'profile.hasDelivery': { ar: 'يوجد توصيل', en: 'Delivery Available' },
  'profile.deliveryQuestion': { ar: 'هل تقدم خدمة التوصيل؟', en: 'Do you offer delivery service?' },
  'profile.saving': { ar: 'جاري الحفظ...', en: 'Saving...' },
  'profile.saveChanges': { ar: 'حفظ التغييرات', en: 'Save Changes' },
  'profile.whatsappRequired': { ar: 'رقم الواتساب مطلوب لتفعيل الصفحة', en: 'WhatsApp number is required to enable the page' },
  'profile.serviceLocation': { ar: 'مكان الخدمة / منطقة التغطية', en: 'Service Location / Coverage Area' },
  'profile.serviceLocationPlaceholder': { ar: 'مثال: عمان - جميع المناطق', en: 'Example: Amman - All areas' },
  'profile.workingHours': { ar: 'أوقات الدوام', en: 'Working Hours' },
  'profile.workingHoursPlaceholder': { ar: 'مثال: 8 صباحاً - 6 مساءً', en: 'Example: 8 AM - 6 PM' },
  'items.title': { ar: 'الخدمات', en: 'Services' },
  'items.addItems': { ar: 'أضف خدماتك مع صورها', en: 'Add your services with images' },
  'items.addItem': { ar: 'إضافة خدمة', en: 'Add Service' },
  'items.editItem': { ar: 'تعديل الخدمة', en: 'Edit Service' },
  'items.addNewItem': { ar: 'إضافة خدمة جديدة', en: 'Add New Service' },
  'items.productImage': { ar: 'صورة الخدمة', en: 'Service Image' },
  'items.uploading': { ar: 'جاري الرفع...', en: 'Uploading...' },
  'items.changeImage': { ar: 'تغيير الصورة', en: 'Change Image' },
  'items.uploadImage': { ar: 'رفع صورة', en: 'Upload Image' },
  'items.imageNote': { ar: 'يتم ضغط الصور تلقائياً لتوفير المساحة', en: 'Images are automatically compressed to save space' },
  'items.itemTitle': { ar: 'العنوان', en: 'Title' },
  'items.titlePlaceholder': { ar: 'اسم الخدمة', en: 'Service name' },
  'items.titleRequired': { ar: 'العنوان مطلوب', en: 'Title is required' },
  'items.description': { ar: 'الوصف', en: 'Description' },
  'items.descriptionPlaceholder': { ar: 'وصف مختصر...', en: 'Brief description...' },
  'items.price': { ar: 'السعر', en: 'Price' },
  'items.pricePositive': { ar: 'السعر يجب أن يكون رقماً موجباً', en: 'Price must be a positive number' },
  'items.priceMax': { ar: 'السعر كبير جداً (الحد الأقصى 99,999,999)', en: 'Price is too large (maximum 99,999,999)' },
  'items.saving': { ar: 'جاري الحفظ...', en: 'Saving...' },
  'items.noItems': { ar: 'لا توجد خدمات', en: 'No services' },
  'items.startAdding': { ar: 'ابدأ بإضافة خدماتك', en: 'Start adding your services' },
  'items.loadError': { ar: 'فشل في تحميل الخدمات', en: 'Failed to load services' },
  'items.updateError': { ar: 'فشل في تحديث الخدمة', en: 'Failed to update service' },
  'items.updated': { ar: 'تم التحديث', en: 'Updated' },
  'items.itemUpdated': { ar: 'تم تحديث الخدمة بنجاح', en: 'Service updated successfully' },
  'items.maxReached': { ar: 'تم الوصول للحد الأقصى', en: 'Maximum limit reached' },
  'items.maxItems': { ar: 'لقد وصلت للحد الأقصى من الخدمات المجانية', en: 'You have reached the maximum free services limit' },
  'items.buyExtraDish': { ar: 'أضف خدمة إضافية - 5 دنانير', en: 'Add extra service - 5 JOD' },
  'items.buyExtraDesc': { ar: 'ادفع 5 دنانير لإضافة خدمة إضافية واحدة لقائمتك', en: 'Pay 5 JOD to add one extra service to your list' },
  'items.addError': { ar: 'فشل في إضافة الخدمة', en: 'Failed to add service' },
  'items.added': { ar: 'تمت الإضافة', en: 'Added' },
  'items.itemAdded': { ar: 'تم إضافة الخدمة بنجاح', en: 'Service added successfully' },
  'items.deleteError': { ar: 'فشل في حذف الخدمة', en: 'Failed to delete service' },
  'items.deleted': { ar: 'تم الحذف', en: 'Deleted' },
  'items.itemDeleted': { ar: 'تم حذف الخدمة', en: 'Service deleted' },
  'items.subscriptionRequired': { ar: 'يجب تفعيل اشتراكك أولاً', en: 'You need to activate your subscription first' },
  'items.subscriptionRequiredDesc': { ar: 'لا يمكنك رفع خدمات حتى تدفع رسوم الاشتراك الشهري (7 دينار)', en: 'You cannot upload services until you pay the monthly subscription fee (7 JOD)' },
  'items.goToPayment': { ar: 'الذهاب للدفع', en: 'Go to Payment' },
  'items.uploadingImage': { ar: 'جاري رفع الصورة...', en: 'Uploading image...' },
  'items.pleaseWait': { ar: 'يرجى الانتظار', en: 'Please wait' },
  'items.imageUploaded': { ar: 'تم رفع الصورة', en: 'Image uploaded' },
  'items.imageUploadedDesc': { ar: 'تم رفع الصورة بنجاح', en: 'Image uploaded successfully' },
  'items.imageUploadError': { ar: 'فشل في رفع الصورة، حاول مرة أخرى', en: 'Failed to upload image, please try again' },
  'items.productCountry': { ar: 'بلد الخدمة', en: 'Service Country' },
  'items.productCategory': { ar: 'نوع الخدمة', en: 'Service Category' },
  'orders.title': { ar: 'الطلبات', en: 'Orders' },
  'orders.manageOrders': { ar: 'إدارة طلبات العملاء', en: 'Manage customer orders' },
  'orders.noOrders': { ar: 'لا توجد طلبات', en: 'No orders' },
  'orders.ordersAppear': { ar: 'ستظهر الطلبات هنا عندما يطلب العملاء خدماتك', en: 'Orders will appear here when customers order your services' },
  'orders.new': { ar: 'جديد', en: 'New' },
  'orders.confirmed': { ar: 'مؤكد', en: 'Confirmed' },
  'orders.completed': { ar: 'مكتمل', en: 'Completed' },
  'orders.cancelled': { ar: 'ملغي', en: 'Cancelled' },
  'orders.loadError': { ar: 'فشل في تحميل الطلبات', en: 'Failed to load orders' },
  'orders.updateError': { ar: 'فشل في تحديث حالة الطلب', en: 'Failed to update order status' },
  'orders.updated': { ar: 'تم التحديث', en: 'Updated' },
  'orders.statusUpdated': { ar: 'تم تحديث حالة الطلب', en: 'Order status updated' },
  'orders.details': { ar: 'تفاصيل الطلب', en: 'Order Details' },
  'orders.customerData': { ar: 'بيانات العميل', en: 'Customer Data' },
  'orders.name': { ar: 'الاسم', en: 'Name' },
  'orders.phone': { ar: 'الجوال', en: 'Phone' },
  'orders.notes': { ar: 'ملاحظات', en: 'Notes' },
  'orders.country': { ar: 'البلد', en: 'Country' },
  'orders.products': { ar: 'الخدمات', en: 'Services' },
  'orders.total': { ar: 'الإجمالي', en: 'Total' },
  'orders.call': { ar: 'اتصال', en: 'Call' },
  'orders.whatsapp': { ar: 'واتساب', en: 'WhatsApp' },
  'orders.hello': { ar: 'مرحباً، بخصوص طلبك:', en: 'Hello, regarding your order:' },
  'aiGuide.title': { ar: 'مرشد خدمات', en: 'Khadamat Guide' },
  'aiGuide.online': { ar: 'متصل الآن', en: 'Online now' },
  'aiGuide.welcome': { ar: 'مرحباً! أنا مرشد خدمات الذكي 👋\n\nكيف يمكنني مساعدتك اليوم؟', en: 'Hello! I am the Khadamat smart guide 👋\n\nHow can I help you today?' },
  'aiGuide.placeholder': { ar: 'اكتب سؤالك...', en: 'Write your question...' },
  'aiGuide.error': { ar: 'عذراً، حدث خطأ. يرجى المحاولة مرة أخرى.', en: 'Sorry, an error occurred. Please try again.' },
  'aiGuide.navigated': { ar: 'تم الانتقال', en: 'Navigated' },
  'aiGuide.navigatedTo': { ar: 'تم الانتقال إلى', en: 'Navigated to' },
  'aiGuide.home': { ar: 'الصفحة الرئيسية', en: 'Home page' },
  'aiGuide.login': { ar: 'صفحة تسجيل الدخول', en: 'Login page' },
  'aiGuide.dashboard': { ar: 'لوحة التحكم', en: 'Dashboard' },
  'aiGuide.terms': { ar: 'الشروط والأحكام', en: 'Terms and conditions' },
  'aiGuide.cart': { ar: 'سلة التسوق', en: 'Shopping Cart' },
  'aiGuide.quickQuestions': { ar: 'أسئلة سريعة:', en: 'Quick questions:' },
  'aiGuide.q1': { ar: 'كيف أبدأ مشروعي؟', en: 'How to start my project?' },
  'aiGuide.q2': { ar: 'كيف أضيف خدماتي؟', en: 'How to add my services?' },
  'aiGuide.q3': { ar: 'خذني للوحة التحكم', en: 'Take me to dashboard' },
  'aiGuide.smartGuide': { ar: 'مرشد ذكي', en: 'Smart Guide' },
  'aiGuide.myAccount': { ar: 'حسابي', en: 'My Account' },
  'notFound.title': { ar: '404', en: '404' },
  'notFound.message': { ar: 'عذراً! الصفحة غير موجودة', en: 'Oops! Page not found' },
  'notFound.backHome': { ar: 'العودة للرئيسية', en: 'Return to Home' },
  'browse.addedToCart': { ar: 'تمت الإضافة للسلة', en: 'Added to cart' },
  'browse.noDishes': { ar: 'لا توجد خدمات', en: 'No services found' },
  'browse.tryChangingFilters': { ar: 'جرب تغيير الفلاتر أو البحث', en: 'Try changing filters or search' },
  'browse.delivery': { ar: 'توصيل', en: 'Delivery' },
  'browse.noMore': { ar: 'لا يوجد المزيد من الطبخات', en: 'No more items' },
  'cart.title': { ar: 'سلة التسوق', en: 'Shopping Cart' },
  'cart.empty': { ar: 'السلة فارغة', en: 'Cart is empty' },
  'cart.noProducts': { ar: 'لم تضف أي خدمات بعد', en: "You haven't added any services yet" },
  'cart.browseProducts': { ar: 'تصفح الخدمات', en: 'Browse Services' },
  'cart.continueShopping': { ar: 'متابعة التسوق', en: 'Continue Shopping' },
  'cart.subtotal': { ar: 'المجموع', en: 'Subtotal' },
  'cart.total': { ar: 'الإجمالي', en: 'Total' },
  'cart.confirmOrder': { ar: 'تأكيد الطلب', en: 'Confirm Order' },
  'cart.orderConfirmed': { ar: 'تم تأكيد الطلب', en: 'Order Confirmed' },
  'cart.orderSentToMerchant': { ar: 'تم إرسال طلبك لمقدم الخدمة وسيتواصل معك قريباً', en: 'Your order was sent to the provider and they will contact you soon' },
  'cart.loginToConfirm': { ar: 'سجل دخولك لتأكيد الطلب', en: 'Login to confirm order' },
  'cart.loginToContinue': { ar: 'يجب تسجيل الدخول لإرسال طلبك', en: 'You need to login to send your order' },
  'cart.viewCookPage': { ar: 'صفحة مقدم الخدمة', en: 'Provider Page' },
  'cart.itemsUnavailable': { ar: 'بعض الخدمات غير متوفرة', en: 'Some services are unavailable' },
  'cart.someItemsRemoved': { ar: 'تم حذف الخدمات غير المتوفرة من السلة', en: 'Unavailable services have been removed from your cart' },
  'cart.orderFailed': { ar: 'فشل في إرسال الطلب، حاول مرة أخرى', en: 'Failed to send order, please try again' },
  'profile.storeName': { ar: 'اسم المتجر', en: 'Store Name' },
  'profile.storeNamePlaceholder': { ar: 'مثال: ورشة أبو أحمد', en: 'Example: Abu Ahmad Workshop' },
  'auth.address': { ar: 'المحافظة', en: 'Governorate' },
  'auth.addressPlaceholder': { ar: 'مثال: عمان - جبل الحسين', en: 'Example: Amman - Jabal Al-Hussein' },
  'auth.addressRequired': { ar: 'يرجى اختيار المحافظة', en: 'Please select a governorate' },
  'auth.selectGovernorate': { ar: 'اختر المحافظة', en: 'Select Governorate' },
  // Dashboard translations
  'dashboard.emergency': { ar: 'طوارئ', en: 'Emergency' },
  'dashboard.ourWork': { ar: 'أعمالنا', en: 'Our Work' },
  'dashboard.ratings': { ar: 'التقييمات', en: 'Ratings' },
  'dashboard.ratingsCount': { ar: 'التقييمات', en: 'Ratings' },
  'dashboard.noRatings': { ar: 'لا توجد تقييمات بعد', en: 'No ratings yet' },
  // Auth page translations
  'auth.loginAsProvider': { ar: 'تسجيل دخول كمزود خدمة', en: 'Login as Service Provider' },
  'auth.loginAsCustomer': { ar: 'تسجيل دخول كعميل', en: 'Login as Customer' },
  'auth.serviceType': { ar: 'نوع الخدمة', en: 'Service Type' },
  'auth.selectServiceType': { ar: 'اختر نوع الخدمة', en: 'Select Service Type' },
  'auth.enableEmergency': { ar: '⚡ تفعيل وضع الطوارئ', en: '⚡ Enable Emergency Mode' },
  'auth.emergencyDesc': { ar: 'للخدمات العاجلة والطارئة', en: 'For urgent and emergency services' },
  'auth.emergencyNotifications': { ar: '🔔 إشعارات فورية للعملاء', en: '🔔 Instant notifications to customers' },
  'auth.emergencyWhatsapp': { ar: '📱 تنبيهات واتساب مباشرة', en: '📱 Direct WhatsApp alerts' },
  'auth.emergencyPriority': { ar: '⭐ أولوية في الظهور', en: '⭐ Priority in display' },
  'auth.categoryRequired': { ar: 'يرجى اختيار نوع الخدمة', en: 'Please select a service type' },
  // Admin new translations
  'admin.unauthorized': { ar: 'غير مصرح لك بالدخول', en: 'Unauthorized access' },
  'admin.ratingDeleted': { ar: 'تم حذف التقييم', en: 'Rating deleted' },
  'admin.extraService': { ar: 'خدمة إضافية', en: 'Extra Service' },
  'admin.subscription': { ar: 'اشتراك', en: 'Subscription' },
  'admin.totalReceipts': { ar: 'إجمالي الوصولات', en: 'Total Receipts' },
  'admin.providers': { ar: 'مقدمي الخدمات', en: 'Providers' },
  'admin.services': { ar: 'الخدمات', en: 'Services' },
  'admin.ratingsTab': { ar: 'التقييمات', en: 'Ratings' },
  'admin.paymentsTab': { ar: 'المدفوعات', en: 'Payments' },
  'admin.manageProviders': { ar: 'إدارة مقدمي الخدمات', en: 'Manage Providers' },
  'admin.inactive': { ar: 'معطّل', en: 'Inactive' },
  'admin.noProviders': { ar: 'لا يوجد مقدمي خدمات', en: 'No providers' },
  'admin.noName': { ar: 'بدون اسم', en: 'No name' },
  'admin.whatsappClicks': { ar: 'نقرة واتساب', en: 'WhatsApp clicks' },
  'admin.delete': { ar: 'حذف', en: 'Delete' },
  'admin.manageServices': { ar: 'إدارة الخدمات', en: 'Manage Services' },
  'admin.noServices': { ar: 'لا توجد خدمات', en: 'No services' },
  'admin.service': { ar: 'الخدمة', en: 'Service' },
  'admin.provider': { ar: 'مقدم الخدمة', en: 'Provider' },
  'admin.allRatings': { ar: 'جميع التقييمات', en: 'All Ratings' },
  'admin.noRatings': { ar: 'لا توجد تقييمات', en: 'No ratings' },
  'admin.customer': { ar: 'العميل', en: 'Customer' },
  'admin.rating': { ar: 'التقييم', en: 'Rating' },
  'admin.comment': { ar: 'التعليق', en: 'Comment' },
  'admin.date': { ar: 'التاريخ', en: 'Date' },
  'admin.all': { ar: 'الكل', en: 'All' },
  'admin.viewReceipt': { ar: 'عرض الوصل', en: 'View Receipt' },
  'admin.accept': { ar: 'قبول', en: 'Accept' },
  'admin.reject': { ar: 'رفض', en: 'Reject' },
  // ServiceSEO translations
  'seo.pageNotFound': { ar: 'الصفحة غير موجودة', en: 'Page not found' },
  'seo.backHome': { ar: 'العودة للرئيسية', en: 'Back to Home' },
  'seo.browseProviders': { ar: 'تصفح مقدمي الخدمة', en: 'Browse Service Providers' },
  'seo.registerAsProvider': { ar: 'سجل كمقدم خدمة', en: 'Register as Provider' },
  'seo.whyChoose': { ar: 'لماذا تختار منصة خدمات؟', en: 'Why choose Khadamat platform?' },
  'seo.trustedProviders': { ar: 'مقدمي خدمة موثوقين', en: 'Trusted providers' },
  'seo.instantEmergency': { ar: 'خدمة طوارئ فورية', en: 'Instant emergency service' },
  'seo.allGovernorates': { ar: 'تغطية جميع المحافظات', en: 'Coverage in all governorates' },
  'seo.realRatings': { ar: 'تقييمات حقيقية', en: 'Real ratings' },
  'seo.servicesIn': { ar: 'خدمات', en: 'services' },
  'seo.inJordan': { ar: 'في الأردن', en: 'in Jordan' },
  'seo.inAllGovernorates': { ar: 'في جميع المحافظات', en: 'in all governorates' },
  'seo.faq': { ar: 'الأسئلة الشائعة', en: 'FAQ' },
  'seo.otherServices': { ar: 'خدمات أخرى', en: 'Other Services' },
  // Terms page translations
  'terms.khadamat': { ar: 'خدمات', en: 'Khadamat' },
  'terms.back': { ar: 'رجوع', en: 'Back' },
  'terms.title': { ar: 'سياسة الخصوصية وإخلاء المسؤولية لمنصة خدمات', en: 'Privacy Policy and Disclaimer for Khadamat Platform' },
  'terms.readCarefully': { ar: 'يرجى قراءة الشروط التالية بعناية قبل التسجيل', en: 'Please read the following terms carefully before registering' },
  'terms.privacyPolicy': { ar: '1. سياسة الخصوصية (Privacy Policy)', en: '1. Privacy Policy' },
  'terms.disclaimer': { ar: '2. إخلاء المسؤولية (Disclaimer)', en: '2. Disclaimer' },
  'terms.aboutUs': { ar: 'من نحن', en: 'About Us' },
  'terms.finalApproval': { ar: '3. الموافقة النهائية', en: '3. Final Approval' },
  'terms.agreeTerms': { ar: 'أوافق على سياسة الخصوصية وإخلاء المسؤولية وشروط استخدام منصة خدمات', en: 'I agree to the Privacy Policy, Disclaimer, and Terms of Use of Khadamat Platform' },
};

interface LanguageContextType { language: Language; setLanguage: (lang: Language) => void; t: (key: string) => string; dir: 'rtl' | 'ltr'; }
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => { const saved = localStorage.getItem('language'); return (saved as Language) || 'ar'; });
  useEffect(() => { localStorage.setItem('language', language); document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; }, [language]);
  const setLanguage = (lang: Language) => { setLanguageState(lang); };
  const t = (key: string): string => { const translation = translations[key]; if (!translation) { console.warn(`Translation missing for key: ${key}`); return key; } return translation[language]; };
  const dir = language === 'ar' ? 'rtl' : 'ltr';
  return (<LanguageContext.Provider value={{ language, setLanguage, t, dir }}>{children}</LanguageContext.Provider>);
};

export const useLanguage = () => { const context = useContext(LanguageContext); if (context === undefined) throw new Error('useLanguage must be used within a LanguageProvider'); return context; };
