// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fooqrkdniswrzwgcytne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvb3Fya2RuaXN3cnp3Z2N5dG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3Mzg5MTMsImV4cCI6MjA4ODMxNDkxM30.px0ExibFbOMoNBw-emojn6k3UbrHsZSda4oFTWPpOis";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});